server:
  port: 8088
  servlet:
    multipart:
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.0.155:3306/wxdemo?serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 123.249.0.155
    port: 6379
    password: hnust123
    database: 1
    timeout: 10000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 20
        min-idle: 10
    jedis:
      pool:
        min-idle: 10
        max-idle: 20
        max-wait: -1ms
        max-active: 200

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
